En Mac esc es el comand mode 

In [1]:
import numpy as np

Python a numpy


In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange

In [5]:
diez = np.arange(0,10)
diez

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## ceros y unos 

In [8]:
ceros_arr = np.zeros(3)
ceros_arr

array([0., 0., 0.])

In [10]:
ceros_mat = np.zeros((3,3))
ceros_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
unos_arr = np.ones(3)
unos_arr

array([1., 1., 1.])

## o

In [45]:
ones = np.zeros(10) +1
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
unos_mat = np.ones((2,2))
unos_mat

array([[1., 1.],
       [1., 1.]])

## linspace

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## matriz identidad (eye)

In [20]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

# Random

## random de dist uniforme [0,1) arrays o mat


In [33]:
np.random.rand(2)

array([0.34057641, 0.2751271 ])

In [34]:
 np.random.rand(2,2)

array([[0.27787178, 0.52684807],
       [0.53908274, 0.0173746 ]])

## random de dist normal arrays o mat

In [30]:
np.random.randn(2)

array([0.38136282, 0.11257515])

## random ent  de dist uni arrays o mat [min, max)

In [32]:
np.random.randint(1,100,10)

array([55, 54, 39, 36, 89, 86, 44, 68,  5, 51])

In [35]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

## shape and Reshape

In [43]:
arr1 = np.random.randint(0,100,25)
arr1.shape

(25,)

In [44]:
arr1.reshape(5,5)

array([[31, 22, 42,  6,  5],
       [26, 35, 82, 28, 68],
       [86, 56, 37, 49,  8],
       [82, 51, 58, 46, 90],
       [36, 60, 49, 63, 82]])

## max y min

In [38]:
arr.max()

24

In [40]:
# Return indices of the maximum values along the given axis.
arr.argmax()

24

In [41]:
arr.min()

0

In [46]:
## array de enteros [10 , 50)

In [50]:
ver = np.arange(10,51)
ver

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [48]:
## enteros pares

In [51]:
evens = ver[ver%2==0]
evens

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [52]:
np.resize(np.arange(.01, 1.01 , 0.01), (10,10))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

## Indexing 

In [55]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [54]:
np.asmatrix([mat[2][1:], mat[3][1:], mat[4][1:]])

matrix([[12, 13, 14, 15],
        [17, 18, 19, 20],
        [22, 23, 24, 25]])

In [56]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [57]:
mat[4]

array([21, 22, 23, 24, 25])

In [58]:
mat.sum()

325

In [59]:
mat.std()

7.211102550927978

In [60]:
mat.sum(axis =0)

array([55, 60, 65, 70, 75])

In [62]:
mat.sum(axis = 1)

array([ 15,  40,  65,  90, 115])

In [63]:
## Truco para strings 

In [64]:
import string
for letter in string.ascii_uppercase:
   print(letter, end =" ")
letters_upp = [letter for letter in string.ascii_uppercase]
letters_upp[0:10]

A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']